services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - DB_HOST=db
      - DB_NAME=tf
      - DB_USER=root
    volumes:
      - .:/var/www/
  db:
    image: mariadb
    restart: always
    user: root
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=tf
    expose:
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: